# -*- coding: utf-8 -*-
"""Python for Everybody.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1svhuckOitONlwRApEj3vhSSbu56MUL2F
"""

print("This is a sample program")

a=5
a=a+2
print(a)

"""while loop"""

x=8
while x>0:
  x=x-1
  print(x)

print("Endoff")

a=5
b=8
c=a*b
print(c)

print("Welcome to Policy premium System")
a= int(input("Total Premium Amount (in Rupees):"))
b= int(input("Duration of premium (in year):"))
c= a//b
print("Your yearly premium amount is",c)
print("Your monthly premium amount is",c//12)

print("Welcome to Policy premium System")
a= int(input("Total Premium Amount (in Rupees):"))
b= int(input("Duration of premium (in year):"))
c= a//b
print("Your yearly premium amount is",c)
print("Your monthly premium amount is",c//12)

a= int(input("Enter Monthly Premium Amount (in Rupees):"))
b= int(input("Enter Duration of premium (in year):"))
c= a*12
d= c*b
print("Your yearly premium amount is",c)
print("Your Total premium amount is",d)

x=25
y=x%4
print(y)

x=4+6**2/3*5
print(x)

x= 'Myself' +' '+ 'Prateek Dutta' +' '+ 'Graduate Data Science Trainee' + ' '+ 'at Konverge.AI Pvt. Ltd.'
print(x)
type(x)

a=int(input('Enter the floor:'))
b=a+1
print("you are in Floor",b)

a= int(input("Enter your Yearly Salary:"))
if a<500000:
  print("You are not required to pay tax")

else:
  print("You need to pay tax as per the rule")

def alpha():
  print("Prateek")
  print("Dutta")
alpha() #invoke the function
print("Hello!")
alpha()

def greet(lang):
  if lang=='es':
    print("Hola")
  elif lang=='fr':
    print("banjour")
  else:
    print("Hello")

greet("en")

def greet():
  return"Hello"

print(greet(),'Prateek')
print(greet(),'Ayush')

def add(a,b):
  addition=a+b
  return addition
x= add(6,4)
print(x)

"""strings

"""

chocolate = 'Melody'
letter = chocolate[4]
print(letter)

chocolate = 'Melody'
print(len(chocolate))

chocolate='Melody'
for letter in chocolate:
  print(letter)

chocolate='Melody'
index=0
while index<len(chocolate):
  letter= chocolate[index]
  print(index,letter)
  index=index+1

chocolate='Kacha Mango Bite'
count=0
for letter in chocolate:
  if letter=='a':
    count=count+1
print(count)

x='PythonisaProgramminglanguage'
print(x[3:7])

friend= ['Ayush', 'Arup', 'Krashank', 'Deep']
for friends in friend:
  print("Happy Independence Day", friends)
print('Done')

total=0
count=0
while True:
  x=input("Enter Number:")
  if x=='Done': break
  value=float(x)
  total=total+value
  count=count+1
average=total/count
print("Average of the number:",average)

"""Dictionary"""

book=dict()
book['Flemingo']=10
book['william']= 11
book['A Common Man Succes']=12
print(book)

sentence= 'My College Registration ID:2019AAIE1111004, My dept.:AI, College area pin:440016'
x= sentence.find(':')
print(x)

import urllib.request, urllib.parse, urllib.error
x=urllib.request.urlopen('https://data.pr4e.org/authors.txt')
for line in x:
  print(line.decode().strip())

import urllib.request, urllib.parse, urllib.error
x=urllib.request.urlopen('https://data.pr4e.org/authors.txt')
count=dict()
for line in x:
  words=line.decode().split()
  for word in words:
    count[word]=count.get(word,0)+1
print(count)

"""Web Scrapping"""

pip install beautifulsoup4

import urllib.request, urllib.parse, urllib.error
from bs4 import BeautifulSoup
url= input('Enter URL:- ')
html=urllib.request.urlopen(url).read()
soup=BeautifulSoup(html,'html.parser')
#Retrieve all of the anchor tags
tags=soup('a')
for tag in tags:
  print(tag.get('href',None))

